CREATE TABLE [Account].[KYCDetails](
	[KYCID] [bigint] IDENTITY(1,1) NOT NULL,
	[KYCGUID] [uniqueidentifier] NOT NULL,
	[UserID] [bigint] NOT NULL,
	[KYCFilePath] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[KYCID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UC_KYCDetails_KYCGUID] UNIQUE NONCLUSTERED 
(
	[KYCGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[KYCGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


GO
ALTER TABLE [Account].[KYCDetails]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [Account].[Users] ([UserId])
GO
ALTER TABLE [Account].[KYCDetails]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [Account].[Users] ([UserId])
GO
ALTER TABLE [Account].[KYCDetails]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [Account].[Users] ([UserId])
GO
ALTER TABLE [Account].[KYCDetails]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [Account].[Users] ([UserId])
GO
ALTER TABLE [Account].[KYCDetails]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [Account].[Users] ([UserId])