CREATE TABLE [Account].[PANDetails](
	[PANID] [bigint] IDENTITY(1,1) NOT NULL,
	[PANGUID] [uniqueidentifier] NOT NULL,
	[UserID] [bigint] NOT NULL,
	[PAN] [varchar](20) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[LastUpdate] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PANID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[PANGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


GO
ALTER TABLE [Account].[PANDetails]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [Account].[Users] ([UserId])
GO
ALTER TABLE [Account].[PANDetails]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [Account].[Users] ([UserId])
GO
ALTER TABLE [Account].[PANDetails]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [Account].[Users] ([UserId])
GO
ALTER TABLE [Account].[PANDetails]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [Account].[Users] ([UserId])
GO
ALTER TABLE [Account].[PANDetails]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [Account].[Users] ([UserId])